# makefile

# set up compiler and options
CC     = g++-2.95
CFLAGS = -g -Wall --pedantic --ansi -fexceptions


# rules
bigint:     bigint.cpp
	$(CC) -o $@ $^ $(CFLAGS) 
	@echo Target $@ complete.

poly:     poly.cpp
	$(CC) -o $@ $^ $(CFLAGS) 
	@echo Target $@ complete.

rational:     rational.cpp
	$(CC) -o $@ $^ $(CFLAGS) 
	@echo Target $@ complete.

graph:     graph.cpp
	$(CC) -o $@ $^ $(CFLAGS) 
	@echo Target $@ complete.

